### ISSUE TITLE
[Airflow] Airflow example dags will be scheduled unexpectedly

### ISSUE THREAD

**Issue by bgeng777** [alibaba/flink-ai-extended#231]
### Describe the bug

The scheduler exits the loop according to following error and leads to the aiflow client wait forever:
```
[2021-05-06 12:05:16,925] {event_based_scheduler_job.py:606} INFO - Starting the scheduler Job
[2021-05-06 12:05:17,023] {dag_processing.py:259} INFO - Launched DagFileProcessorManager with pid: 82829
[2021-05-06 12:05:17,124] {base.py:166} INFO - Scheduler started
[2021-05-06 12:05:17,154] {event_based_scheduler_job.py:189} INFO - Found 0 dags not exists in DAG folder, recovered from DB. Dags' path: []
[2021-05-06 12:05:17,155] {event_based_scheduler_job.py:190} INFO - Waiting for executor recovery...
[2021-05-06 12:05:17,155] {local_executor.py:395} INFO - Start to recover LocalExecutor.
[2021-05-06 12:05:17,158] {event_based_scheduler_job.py:194} INFO - Recovering 0 messages of last scheduler job with id: None
[2021-05-06 12:05:17,159] {event_based_scheduler_job.py:121} INFO - Starting the scheduler.
[2021-05-06 12:05:17,171] {event_based_scheduler_job.py:273} ERROR - DAG 'example_passing_params_via_test_command' not found in serialized_dag table
Traceback (most recent call last):
  File "/Users/kenken/samuel/lib/python3.7/site-packages/airflow/contrib/jobs/event_based_scheduler_job.py", line 242, in _create_dag_run
    dag = self.dagbag.get_dag(dag_id, session=session)
  File "/Users/kenken/samuel/lib/python3.7/site-packages/airflow/utils/session.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/Users/kenken/samuel/lib/python3.7/site-packages/airflow/models/dagbag.py", line 171, in get_dag
    self._add_dag_from_db(dag_id=dag_id, session=session)
  File "/Users/kenken/samuel/lib/python3.7/site-packages/airflow/models/dagbag.py", line 227, in _add_dag_from_db
    raise SerializedDagNotFound(f"DAG '{dag_id}' not found in serialized_dag table")
airflow.exceptions.SerializedDagNotFound: DAG 'example_passing_params_via_test_command' not found in serialized_dag table
[2021-05-06 12:05:18,227] {settings.py:52} INFO - Configured default timezone Timezone('UTC')
```
### To Reproduce
Steps to reproduce the behavior (if you can):
1. Submit a '...'
3. See error

**Comment by bgeng777** [comment]
Need more info on reproducing this error.
