### ISSUE TITLE
[Flink AI Flow] EventBasedScheduler bug cause execute loop exited

### ISSUE THREAD

**Issue by jiangxin369** [alibaba/flink-ai-extended#543]
### Describe the bug
```
[2021-09-10 10:05:00,035] {dagrun.py:457} INFO - Marking run <DagRun example_bash_operator_v2 @ 2021-09-08 02:00:00+00:00: scheduled__2021-09-08T02:00:00+00:00, externally triggered: False> successful
[2021-09-10 10:05:00,083] {event_based_scheduler_job.py:673} ERROR - Exception when executing scheduler, '>' not supported between instances of 'NoneType' and 'datetime.datetime'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/contrib/jobs/event_based_scheduler_job.py", line 663, in _execute
    self._run_scheduler_loop()
  File "/usr/local/lib/python3.7/site-packages/airflow/contrib/jobs/event_based_scheduler_job.py", line 682, in _run_scheduler_loop
    should_continue = self.scheduler.schedule()
  File "/usr/local/lib/python3.7/site-packages/airflow/contrib/jobs/event_based_scheduler_job.py", line 167, in schedule
    self._remove_periodic_events(event.run_id)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/session.py", line 65, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/contrib/jobs/event_based_scheduler_job.py", line 236, in _remove_periodic_events
    dag = self.dagbag.get_dag(dag_id=dagruns[0].dag_id, session=session)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/session.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 187, in get_dag
    if sd_last_updated_datetime > self.dags_last_fetched[dag_id]:
TypeError: '>' not supported between instances of 'NoneType' and 'datetime.datetime'
[2021-09-10 10:05:00,087] {event_based_scheduler_job.py:675} INFO - Exited execute loop
```

### To Reproduce
Steps to reproduce the behavior (if you can):
1. Submit a '...'
3. See error

**Comment by jiangxin369** [comment]
Fixed in https://github.com/alibaba/flink-ai-extended/pull/586
